# Generated by Django 5.2 on 2025-05-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_producto_pedidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default=1, upload_to='productos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20),
        ),
    ]
