# Generated by Django 5.2 on 2025-05-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_producto_foto_alter_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('cocteles', 'Cócteles'), ('bebidas_calientes', 'Bebidas Calientes'), ('postres', 'Postres')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
