# Generated by Django 5.2 on 2025-05-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_producto_categoria_alter_producto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='opciones',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
