# Generated by Django 5.2 on 2025-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_producto_opciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='opciones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
