# Generated by Django 5.2 on 2025-05-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_producto_opciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='opciones',
            field=models.TextField(blank=True, help_text='Escribe las opciones separadas por comas. Ej: Capuchino vainilla, Capuchino caramelo'),
        ),
    ]
