# Generated by Django 5.2 on 2025-05-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
