# Generated by Django 5.2 on 2025-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Cocteles', [('Cliente', 'Coctel.html'), ('Mesero', 'Cocteles.html')]), ('Cervezas', [('Cliente', 'Cervezas.html'), ('Mesero', 'CervezasArtesanales.html')]), ('Cigarrillos', [('Cliente', 'Cigarrillo.html'), ('Mesero', 'Cigarrillos.html')]), ('Para Picar', [('Cliente', 'Picar.html'), ('Mesero', 'Para_picar.html')]), ('Bebidas Frias', [('Cliente', 'Bebida_fria.html'), ('Mesero', 'bebidas_frias.html')]), ('Bebidas Calientes', [('Cliente', 'bebida_caliente.html'), ('Mesero', 'bebidas_calientes.html')])], max_length=30),
        ),
    ]
