# Generated by Django 5.2 on 2025-05-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Coctel', 'Cócteles'), ('bebida_caliente', 'Bebidas Calientes'), ('Bebida_fria', 'Bebidas Frias'), ('Cerveza', 'Cervezas'), ('Cigarrillo', 'Cigarrillos'), ('Picar', 'Para Picar')], max_length=30),
        ),
    ]
