# Generated by Django 5.2 on 2025-05-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_actividadreciente'),
        ('inicio', '0017_alter_producto_categoria'),
    ]

    operations = [
    ]
