# Generated by Django 5.2 on 2025-05-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0017_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='id_mesa',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='Usuario',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(max_length=50)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inicio.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
