# Generated by Django 5.2 on 2025-05-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0018_merge_20250528_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('es_principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Coctel', 'Cócteles'), ('bebida_caliente', 'Bebidas Calientes'), ('Bebida_fria', 'Bebidas Frias'), ('Cerveza', 'Cervezas'), ('Cigarrillo', 'Cigarrillos'), ('Picar', 'Para Picar')], default='bebida_fria', max_length=50),
        ),
    ]
