# Generated by Django 5.2 on 2025-05-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0018_remove_pedidos_usuario_remove_pedidos_id_mesa_and_more'),
        ('inicio', '0020_alter_galeriafoto_options_and_more'),
    ]

    operations = [
    ]
