# Generated by Django 5.2 on 2025-05-31 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0021_merge_20250530_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['numero'], 'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AlterModelOptions(
            name='pedidodetalle',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedidos'},
        ),
        migrations.AddField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En Limpieza'), ('reservada', 'Reservada')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='mesa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mesero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pedidodetalle',
            unique_together={('pedido', 'producto')},
        ),
    ]
