# Generated by Django 5.2 on 2025-05-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0023_configuraciongeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(help_text='Capacidad de personas que la mesa puede albergar'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En Limpieza')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la mesa está activa para su uso.'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(help_text='Número único de la mesa (ej. 1, 2, 3)', unique=True),
        ),
    ]
