# Generated by Django 5.2 on 2025-05-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0025_pedido_estado_pedido_fecha_finalizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_finalizacion',
        ),
    ]
