# Generated by Django 5.1.1 on 2025-06-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0021_merge_20250530_1351'),
        ('inicio', '0026_alter_pedido_options_and_more'),
    ]

    operations = [
    ]
