# Generated by Django 5.2 on 2025-06-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0027_merge_20250601_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.IntegerField(default=0, help_text='Cantidad de productos disponibles'),
        ),
    ]
