# Generated by Django 5.2 on 2025-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0028_producto_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
